function R = reconstruct_laplacian_pyramid( pyr )
% pyr: Laplacian pyramid generated by function 'laplacian_pyramid'

row = size(pyr{1}, 1);
col = size(pyr{1}, 2);
level = length(pyr);

R = pyr{level};

for n = level-1:-1:1
    odd = 2 * size( R ) - size( pyr{ n } );
    R = pyr{ n } + UpSize( R, odd );  
end